### ISSUE TITLE
Integrate augmentations from torchio

### ISSUE THREAD

**Issue by Luab** [vbakhteev/CT-aorta-segmentation#13]
https://github.com/fepegar/torchio - has some cool augmentations and samplers. Make our code compatible with theirs and create example notebook showing effects of different augmentations on CT scans.

**Comment by vbakhteev** [comment]
Spent 3.5h

**Comment by fepegar** [comment]
Thanks for using TorchIO and sharing your code! I went through it and saw that you need to read DICOM files. I added support for that in https://github.com/fepegar/torchio/commit/0826af89ff64d9df07a4651547696df5a8ef8abc

Although I see that you do some filtering too, hopefully this feature will be useful for you.

Don't hesitate to give feedback and request more features.

**Comment by vbakhteev** [comment]
@fepegar Thank you for your fast feature delivery! I think a lot of people will use torchio with DICOM files.

Loading DICOM files works great. However, during transform, I met a warning about having negative values, because DICOM values could range from -1024 to +3072.
Will it affect something? If so, then we need some way to handle this.

**Comment by fepegar** [comment]
I guess you're using one of the MRI k-space augmentations (are you sure that's useful for CT?).

The warning is telling you that your negative values will be made positive after only the absolute value of the inverse Fourier transform is kept. You could use `torchio.tranforms.Rescale` to rescale your data to values >= 0, maybe.
